### ISSUE TITLE
Can't find the keys in Redis

### ISSUE THREAD

**Issue by kirstyannepollock** [swarthy/redis-semaphore#10]
Just curious, I should be able to see the keys generated by Mutex in Redis by using 

`scan 0 MATCH *mutex:*` 

right? Because I can't. 

I am definitely on the right Redis instance because when I stop that instance I get back `ERROR: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.`

What subtle/dumb thing have I done wrong....?

**Comment by swarthy** [comment]
Are you sure that you run ```scan ...``` when mutex is acquired?

**Comment by kirstyannepollock** [comment]
After it is acquired. Haven't tried in code, just the redis-cli. I mean it clearly works in code, if I try again to acquire it fails, as expected. I was just curious, becasuse if I need to do any clear up of mutexes with long expiry periods during testing, I would like to see them. I guess it will work when the whole app is up and running - I will try that.
