### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by luislobo** [swarthy/redis-semaphore#137]
Hi,

Our team detected that there are breaking changes coming from an old version (1.x) to 3.1.0+

The CHANGELOG.md mentions about a breaking change, but it says to replace from `FairSemaphore` to `Semaphore` but it doesn't warn that the `acquire` method no longer returns a boolean, and rather, throws when it cannot acquire, and returns nothing.

I think it would be good to add this into the CHANGELOG.md entry, in case other are coming from an old version (like us).

Here's a PR: https://github.com/swarthy/redis-semaphore/pull/136

Thank you!

Luis

**Comment by swarthy** [comment]
Hi, merged #136. Thanks!
