### ISSUE TITLE
ioredis.Cluster is unsupported?

### ISSUE THREAD

**Issue by awill1988** [swarthy/redis-semaphore#15]
Hello,

Thank you for writing this library. Our team wants to use this in production as we find it very valuable for our use case.

As we went up our deployment chain, we go from single instance Redis to clustered. We encountered this and looking at the code it seems that a cluster configuration is not supported. When passing in our Cluster client instance for ioredis, we get:

`'"client" must be instance of ioredis client'` error.

Is this by design?

Would you accept a MR that changes `RedisMutex` from this:

```
if (!(client instanceof Redis)) {
      throw new Error('"client" must be instance of ioredis client')
}
```

to this:

```
if (!(client instanceof Redis) && !(client instanceof Redis.Cluster)) {
      throw new Error('"client" must be instance of ioredis client')
}
```

**Comment by awill1988** [comment]
Added a pull request here #16

**Comment by swarthy** [comment]
Added check in v2.1.0
