### ISSUE TITLE
Support for max request per seconds in semaphore

### ISSUE THREAD

**Issue by knation** [swarthy/redis-semaphore#174]
In addition to max concurrent locks, provide the ability to limit the max number of locks that can be acquired per second. Similar to functionality of https://github.com/SGrondin/bottleneck.

**Comment by swarthy** [comment]
Sorry, rate limiting is out of scope this library.
You can implement your custom rate limit algorythm (for example https://redis.com/glossary/rate-limiting/) and use it alongside with `redis-semaphore` by specifing same `resource` keys in both.

**Comment by mbrevda** [comment]
Just came across this lib and immediately switched to it. Seems so much better than the others! Thanks!

> Just came across this lib and immediately switched to it. Seems so much better than the others!

Do you perhaps have a demo or sample?

> rate limiting is out of scope this library.

ohhh, shame! Is this something you'd be willing to reconsider?
