### ISSUE TITLE
Mutex silently reacquires lock when expired between refreshes

### ISSUE THREAD

**Issue by NilSet** [swarthy/redis-semaphore#175]
When a mutex instance's scheduled lock refresh is delayed, the lock may expire. This leaves a gap of time for another mutex instance to acquire and release the lock before the first instance's refresh runs. In this case, the first mutex **silently** re-acquires the lock, hiding the fact that mutual exclusion was not in fact guaranteed during its lifetime.

If the lock is expired at the time of going to refresh the lock, the mutex should call the onLockLost callback, to signal that the mutex guarantee was not held.

**Comment by swarthy** [comment]
Thanks! I will fix that soon.
