### ISSUE TITLE
let reply = await semaphore.acquire()

### ISSUE THREAD

**Issue by agiterman1** [swarthy/redis-semaphore#19]
semaphore.acquire() does not return success / fail

reply is undefined

**Comment by swarthy** [comment]
Correct.
```.acquire()``` will throw ```TimeoutError``` on timeout and ```ioredis``` native errors if any happend.
You should wrap ```.acquire``` in additional ```try/catch``` block to handle fail.
I usually do something like:
```typescript
async function requestToLimitedAPI(params) {
  await semaphore.acquire()
  try {
     // request
  } finally {
    await semaphore.release()
  }
}

async function myLogic() {
  try {
    await requestToLimitedAPI(params1)
    await requestToLimitedAPI(params2)
    // ...
  } catch (err) {
     console.error(err)
  }
}
```

**Comment by agiterman1** [comment]
thanks.

**Comment by agiterman1** [comment]
thanks.
