### ISSUE TITLE
Support redis cluster/multi nodes with redlock algo

### ISSUE THREAD

**Issue by Sytten** [swarthy/redis-semaphore#21]
Hi me again!
I switched my semaphores to the lib, but I am still using the mutex/lock from `node-redlock` because it supports the [redlock](https://redis.io/topics/distlock#the-redlock-algorithm) algorithm. Basically it ensures that the slave instances are also pinged in the lock process so even if there is a failover from the master there is no chance that a concurrent job can acquire a lock it wasn't supposed to.
It might be hard/time consuming to do, so this is really more a wish if/when you have time :)
Thanks!

**Comment by swarthy** [comment]
RedlockMutex, RedlockSemaphore, RedlockMultiSemaphore added in v4
