### ISSUE TITLE
Node-redis support

### ISSUE THREAD

**Issue by krtk6160** [swarthy/redis-semaphore#25]
Is there any way to use this library with [node-redis](https://www.npmjs.com/package/redis) rather than ioredis?

**Comment by krtk6160** [comment]
> No, ioredis methods return promises, meanwhile node-redis has callback interface, so they are incompatible.

We use [async-redis](https://www.npmjs.com/package/async-redis) to make node-redis work with promises. If I somehow bypass the check that checks the instance of the client, would it work?

**Comment by swarthy** [comment]
I dont think so

**Comment by krtk6160** [comment]
Okay, thanks!

**Comment by rawnsley** [comment]
[node-redis](https://github.com/redis/node-redis) supports promises natively now and it is still the default recommended client for nodejs, so it's probably worth considering adding support.

**Comment by swarthy** [comment]
@rawnsley PR with adding support for node-redis is welcome

**Comment by punkpeye** [comment]
Came here looking for the same

**Comment by punkpeye** [comment]
For others coming here, I found this to be a viable alternative, though does not seem to be equivalent implementation

https://www.npmjs.com/package/simple-redis-mutex

**Comment by rmartins0** [comment]
What is the status of this as of the year 2026?
